### ISSUE TITLE
Unable to authenicate via SSO with Datadog 

### ISSUE THREAD

**Issue by WillCohenInfotrack** [DataDog/datadog-for-visual-studio#1]
I think the signin url should be configurable to be able to point to our dedicated datadog SSO signin route.. otherwise it only supports logging in with Username and password routes.

![image](https://github.com/DataDog/datadog-for-visual-studio/assets/12131516/85781ef4-4e72-4143-945b-344c4b863966)

**Comment by jfree** [comment]
Thanks for your feedback.  We are working with our Authentication team to find a solution for this.

**Comment by mattwill09** [comment]
Any updates on the status of this issue?

**Comment by jfree** [comment]
Thanks for your interest, our Authentication team is going to work on this issue in Q2.

**Comment by Vomain** [comment]
Hi all!
This is still a high priority for us. We're actively working on fixing this, we should have this available before the end of Q3. Sorry for the delay!

**Comment by alonam** [comment]
Hi @WillCohenInfotrack @mattwill09 
Thank you for your patience. The single sign-on authentication is now supported.
Please try to login again, and let us know whether it works for you.
In the login screen, click the link "Using single sign-on?" and follow the on-screen instructions.
Looking forward for your feedback

**Comment by alonam** [comment]
Single sign-on authentication is now supported.
