### ISSUE TITLE
Invalid Organization ID

### ISSUE THREAD

**Issue by davidaleu** [DataDog/datadog-for-visual-studio#2]
I've logged in to my organization but whenever I click on a Datadog error to see it in Visual Studio I get this:

![image](https://github.com/user-attachments/assets/8d93a9d8-8a6f-40cd-8040-aaaaf8823c48)

Any ideas?

**Comment by jfree** [comment]
Hi David, thanks for the report. I presume you are clicking a `View in Visual Studio` button at the top of an APM Error Tracking issue?  If that's the case, could you right-click the button and copy the link and tell us what you see (if you prefer not to post the link here, email to team-ide-integration@datadoghq.com works also).

![image](https://github.com/user-attachments/assets/4dcb4fe4-f6dc-4398-8b59-6ace027df382)

Our internal ticket reference for tracking is IDE-3249.

**Comment by alonam** [comment]
Hi @davidaleu 
The link on the Datadog website has been fixed. You should be able to open insights in Visual Studio now.
Tested with the latest version v1.6.1
Please try again and let us know whether you experience any further issues.
Thank you

**Comment by davidaleu** [comment]
thank you I can confirm is now working
